/**
 * Regenerates PLACEHOLDERS.md from the registry in src/data/placeholders/ and cross-checks it
 * against the source code.
 *
 *   npm run placeholders          # write PLACEHOLDERS.md, fail on unknown/duplicate ids
 *   npm run placeholders -- --check   # same checks, do not write
 *
 * An id counts as "used" when it appears in source as <Ph id="…"> / <PhLink id="…">, as a quoted
 * string argument to ph(), valueOf() or getPlaceholder(), or as a `ph: '…'` field in a data file.
 */
import fs from 'node:fs';
import path from 'node:path';
import { groups } from '../src/data/placeholders/index';

const root = path.resolve(import.meta.dirname, '..');
const checkOnly = process.argv.includes('--check');
const problems: string[] = [];

// 1. Duplicate ids across group files.
const owner = new Map<string, string>();
for (const [group, defs] of Object.entries(groups)) {
  for (const id of Object.keys(defs)) {
    if (owner.has(id)) problems.push(`Duplicate id "${id}" in groups "${owner.get(id)}" and "${group}"`);
    owner.set(id, group);
  }
}

// 2. Ids referenced in source.
const used = new Map<string, Set<string>>();
const walk = (dir: string): string[] =>
  fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) => {
    const p = path.join(dir, d.name);
    if (d.isDirectory()) return d.name === 'placeholders' && dir.endsWith('data') ? [] : walk(p);
    return /\.(astro|ts|tsx|mjs|js)$/.test(d.name) ? [p] : [];
  });
const patterns = [
  /<Ph(?:Link)?\b[^>]*?\bid=["']([^"']+)["']/g, // <Ph id="org.email" /> and <PhLink id="…" />
  /\b(?:ph|valueOf|getPlaceholder)\(\s*["']([\w.-]+)["']/g,
  /\bph:\s*["']([\w.-]+)["']/g, // data files: { ph: 'events.1.date' }
];
for (const file of walk(path.join(root, 'src'))) {
  const text = fs.readFileSync(file, 'utf8');
  for (const re of patterns) {
    for (const m of text.matchAll(re)) {
      const id = m[1];
      if (!owner.has(id)) problems.push(`Unknown placeholder id "${id}" in ${path.relative(root, file)}`);
      else (used.get(id) ?? used.set(id, new Set()).get(id)!).add(path.relative(root, file));
    }
  }
}
const unused = [...owner.keys()].filter((id) => !used.has(id));

// 3. Write PLACEHOLDERS.md.
const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const titles: Record<string, string> = {
  global: 'Organization-wide (footer, contact, metadata)',
  home: 'Home page (/)',
  about: 'About page (/about/)',
  events: 'Events & Competitions page (/events/)',
  resources: 'Student Resources page (/resources/)',
  'get-involved': 'Get Involved page (/get-involved/)',
  privacy: 'Privacy Notice (/privacy/)',
};
let total = 0;
let filled = 0;
const sections = Object.entries(groups)
  .filter(([, defs]) => Object.keys(defs).length)
  .map(([group, defs]) => {
    const rows = Object.entries(defs).map(([id, d]) => {
      total++;
      if (d.value !== null) filled++;
      return `| \`${id}\` | ${esc(d.label)} | ${esc(d.note)} | ${d.example ? `\`${esc(d.example)}\`` : ''} | ${d.value === null ? '☐ to fill' : '☑ filled'} |`;
    });
    return `## ${titles[group] ?? group}\n\nFile: \`src/data/placeholders/${group}.ts\`\n\n| ID | What to provide | Where / notes | Example format | Status |\n|---|---|---|---|---|\n${rows.join('\n')}\n`;
  });

const md = `# Placeholders to fill in

This file is generated by \`npm run placeholders\` from \`src/data/placeholders/\`. Do not edit it by hand.

Every real-world detail the site needs but that we do not know yet shows on the site as a
marked placeholder chip. To fill one in, open the file listed for its section, find the id, and replace
\`value: null\` with the real value (a string), e.g. \`value: 'hello@example.org'\`. Every place that
uses it updates automatically. Then run \`npm run placeholders\` to refresh this list.

**${total - filled} of ${total} still to fill.**

${sections.join('\n')}`;

if (!checkOnly) fs.writeFileSync(path.join(root, 'PLACEHOLDERS.md'), md);

console.log(`${total} placeholders (${total - filled} unfilled) across ${Object.keys(groups).length} groups.`);
if (unused.length) console.log(`Declared but not referenced in src/: ${unused.join(', ')}`);
if (problems.length) {
  console.error(problems.map((p) => `✗ ${p}`).join('\n'));
  process.exit(1);
}
